feat: added if statement

diff --git a/.github/workflows/branch-restrictions.yml b/.github/workflows/branch-restrictions.yml
--- a/.github/workflows/branch-restrictions.yml
+++ b/.github/workflows/branch-restrictions.yml
@@ -17,4 +17,8 @@ jobs:
         run: |
           TARGET_BRANCH="${{ github.base_ref }}"
           SOURCE_BRANCH="${{ github.head_ref }}"
-          echo "Hello world"
+          
+          if [[ "$TARGET_BRANCH" == "main" && ! "$SOURCE_BRANCH" =~ ^(develop|hotfix/.+)$ ]]; then
+            echo "Error: PR to 'main' branch is only allowed from 'develop' or 'hotfix/*' branches."
+            exit 1
+          fi
